# Generated by Django 3.0.7 on 2020-06-18 22:29

import datetime
from django.db import migrations, models
import websites.models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websites',
            options={'verbose_name': 'Website', 'verbose_name_plural': 'Websites'},
        ),
        migrations.AddField(
            model_name='websites',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='websites',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 19, 28, 59, 208756)),
        ),
        migrations.AlterField(
            model_name='websites',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=websites.models.icon_path),
        ),
    ]
