# Generated by Django 3.0.7 on 2020-06-18 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_auto_20200618_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='local_timezone',
            field=models.CharField(default='America/Sao_Paulo', max_length=50),
        ),
        migrations.AlterField(
            model_name='websites',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 20, 52, 4, 834893)),
        ),
    ]
