# Generated by Django 3.0.7 on 2020-06-20 20:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import websites.models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_auto_20200619_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('images', models.ImageField(blank=True, null=True, upload_to=websites.models.image_path)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 6, 20, 17, 41, 50, 626021))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('calculation', models.CharField(choices=[('1', 'Sum'), ('2', 'Average')], default='1', max_length=1)),
                ('minimum', models.PositiveIntegerField(default=1)),
                ('maximum', models.PositiveIntegerField(default=1)),
                ('can_repeat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.AddField(
            model_name='websites',
            name='color',
            field=models.CharField(default='red', max_length=20),
        ),
        migrations.AlterField(
            model_name='websites',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 17, 41, 50, 483755)),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to=websites.models.image_path)),
                ('calculation', models.CharField(choices=[('1', 'Unique Price'), ('2', 'Total Sum')], default='1', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('position', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_highlight', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('start_at', models.DateField(blank=True, null=True)),
                ('end_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.Categories')),
                ('websites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.Websites')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to=websites.models.image_path)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('minimum', models.PositiveIntegerField(default=0)),
                ('maximum', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.Groups')),
                ('websites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.Websites')),
            ],
            options={
                'verbose_name': ('Option',),
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.Products'),
        ),
        migrations.AddField(
            model_name='groups',
            name='websites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.Websites'),
        ),
        migrations.AddField(
            model_name='categories',
            name='websites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.Websites'),
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('images', models.ImageField(upload_to=websites.models.image_path)),
                ('position', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('websites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.Websites')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.UniqueConstraint(fields=('websites', 'title'), name='unique_product'),
        ),
        migrations.AddConstraint(
            model_name='options',
            constraint=models.UniqueConstraint(fields=('websites', 'groups', 'title'), name='unique_options'),
        ),
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.UniqueConstraint(fields=('websites', 'products', 'title'), name='unique_group'),
        ),
        migrations.AddConstraint(
            model_name='categories',
            constraint=models.UniqueConstraint(fields=('websites', 'title'), name='unique_category'),
        ),
    ]
