# Generated by Django 3.0.7 on 2020-06-22 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_auto_20200621_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 22, 31, 16, 788882)),
        ),
        migrations.AlterField(
            model_name='websites',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 22, 31, 16, 693858)),
        ),
    ]
