# Generated by Django 3.0.7 on 2020-06-22 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_auto_20200621_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='link',
            field=models.SlugField(default='#', max_length=30),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 13, 43, 36, 730376)),
        ),
        migrations.AlterField(
            model_name='websites',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 13, 43, 36, 610449)),
        ),
    ]
