# Generated by Django 3.0.7 on 2020-06-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0009_auto_20200622_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='link',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
