# Generated by Django 3.0.7 on 2020-06-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0010_auto_20200622_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('websites', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='websites.Websites')),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('twitch', models.CharField(blank=True, max_length=100, null=True)),
                ('discord', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.RemoveField(
            model_name='websites',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='websites',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='websites',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='websites',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='websites',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='websites',
            name='youtube',
        ),
    ]
