# Generated by Django 3.0.7 on 2020-06-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0011_auto_20200623_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='home',
            field=models.CharField(default='Highlight', max_length=20),
        ),
        migrations.AlterField(
            model_name='websites',
            name='local_timezone',
            field=models.CharField(default='auto', max_length=50),
        ),
    ]
