# Generated by Django 3.0.7 on 2020-06-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0012_auto_20200625_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='currency',
            field=models.CharField(default='auto', max_length=10),
        ),
    ]
