# Generated by Django 3.0.7 on 2020-06-25 21:30

from django.db import migrations, models
import websites.models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0013_websites_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='home_images',
            field=models.ImageField(blank=True, null=True, upload_to=websites.models.icon_path),
        ),
        migrations.AlterField(
            model_name='categories',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=websites.models.icon_path),
        ),
    ]
