# Generated by Django 3.0.7 on 2020-06-28 03:02

from django.db import migrations, models
import django.db.models.deletion
import websites.models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0014_auto_20200625_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('websites', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='websites.Websites')),
                ('navbar_top', models.CharField(default='red', max_length=20)),
                ('categories', models.CharField(default='red', max_length=20)),
                ('cards', models.CharField(default='red', max_length=20)),
                ('footer', models.CharField(default='red', max_length=20)),
                ('products', models.CharField(default='black', max_length=20)),
                ('text', models.CharField(default='white', max_length=20)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('websites', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='websites.Websites')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('twitch', models.CharField(blank=True, max_length=100, null=True)),
                ('discord', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('websites', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='websites.Websites')),
                ('shortcut', models.ImageField(blank=True, null=True, upload_to=websites.models.icon_path)),
                ('account', models.ImageField(blank=True, null=True, upload_to=websites.models.icon_path)),
                ('cart', models.ImageField(blank=True, null=True, upload_to=websites.models.icon_path)),
                ('search', models.ImageField(blank=True, null=True, upload_to=websites.models.icon_path)),
                ('home', models.ImageField(blank=True, null=True, upload_to=websites.models.icon_path)),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
            },
        ),
        migrations.RemoveField(
            model_name='websites',
            name='color',
        ),
        migrations.RemoveField(
            model_name='websites',
            name='email',
        ),
        migrations.RemoveField(
            model_name='websites',
            name='home_images',
        ),
        migrations.RemoveField(
            model_name='websites',
            name='images',
        ),
        migrations.RemoveField(
            model_name='websites',
            name='telephone',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
