# Generated by Django 3.0.7 on 2020-06-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0015_auto_20200628_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='active',
            field=models.CharField(default='E62D2D', max_length=6),
        ),
        migrations.AlterField(
            model_name='colors',
            name='cards',
            field=models.CharField(default='F03333', max_length=6),
        ),
        migrations.AlterField(
            model_name='colors',
            name='categories',
            field=models.CharField(default='F03333', max_length=6),
        ),
        migrations.AlterField(
            model_name='colors',
            name='footer',
            field=models.CharField(default='F03333', max_length=6),
        ),
        migrations.AlterField(
            model_name='colors',
            name='navbar_top',
            field=models.CharField(default='0080FF', max_length=6),
        ),
        migrations.AlterField(
            model_name='colors',
            name='products',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='colors',
            name='text',
            field=models.CharField(default='FFFFFF', max_length=6),
        ),
    ]
