# Generated by Django 3.0.7 on 2020-06-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0016_auto_20200628_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colors',
            old_name='products',
            new_name='title',
        ),
    ]
