# Generated by Django 3.0.7 on 2020-06-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0018_auto_20200628_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colors',
            old_name='cards_hover',
            new_name='title_hover',
        ),
    ]
