# Generated by Django 3.0.7 on 2020-06-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0019_auto_20200628_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
