# Generated by Django 3.0.7 on 2020-06-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0020_auto_20200628_2220'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categories',
            name='unique_category',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='color',
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='categories',
            constraint=models.UniqueConstraint(fields=('websites', 'slug'), name='unique_category'),
        ),
    ]
