# Generated by Django 3.0.7 on 2020-06-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0021_auto_20200629_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
