# Generated by Django 3.0.7 on 2020-07-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0025_auto_20200629_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
