# Generated by Django 3.0.7 on 2020-07-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0026_auto_20200630_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
