# Generated by Django 3.0.7 on 2020-07-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0027_auto_20200703_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
