# Generated by Django 3.0.7 on 2020-07-04 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0028_auto_20200703_2123'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groups',
            name='unique_group',
        ),
        migrations.RemoveConstraint(
            model_name='options',
            name='unique_options',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='is_highlight',
            new_name='show_home',
        ),
        migrations.RenameField(
            model_name='websites',
            old_name='local_timezone',
            new_name='timezone',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='can_repeat',
        ),
        migrations.RemoveField(
            model_name='products',
            name='calculation',
        ),
        migrations.RemoveField(
            model_name='products',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='products',
            name='start_at',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
        migrations.AddField(
            model_name='colors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='price_type',
            field=models.CharField(choices=[('1', 'Independent'), ('2', 'Partially Dependent'), ('3', 'Totally Dependent')], default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='groups',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='icons',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icons',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price_type',
            field=models.CharField(choices=[('1', 'Independent'), ('2', 'Partially Dependent'), ('3', 'Totally Dependent')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='options',
            name='maximum',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='websites',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.UniqueConstraint(fields=('products', 'title'), name='unique_group'),
        ),
        migrations.AddConstraint(
            model_name='options',
            constraint=models.UniqueConstraint(fields=('groups', 'title'), name='unique_options'),
        ),
    ]
