# Generated by Django 3.0.7 on 2020-07-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0030_groups_user_input'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colors',
            old_name='navbar_top',
            new_name='navbar',
        ),
    ]
