# Generated by Django 3.0.7 on 2020-07-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0031_auto_20200705_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
