# Generated by Django 3.0.7 on 2020-07-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0032_products_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='images',
            new_name='icon',
        ),
        migrations.AddField(
            model_name='groups',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='options',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
