# Generated by Django 3.0.7 on 2020-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0034_auto_20200711_1003'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='products',
            name='unique_product',
        ),
        migrations.AddField(
            model_name='groups',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='options',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
