# Generated by Django 3.0.7 on 2020-07-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0036_auto_20200711_1022'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groups',
            name='unique_group',
        ),
        migrations.RemoveConstraint(
            model_name='options',
            name='unique_options',
        ),
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.UniqueConstraint(fields=('products', 'slug'), name='unique_group'),
        ),
        migrations.AddConstraint(
            model_name='options',
            constraint=models.UniqueConstraint(fields=('groups', 'slug'), name='unique_options'),
        ),
    ]
