# Generated by Django 3.0.7 on 2020-07-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0037_auto_20200711_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
