# Generated by Django 3.0.8 on 2020-12-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0038_auto_20200713_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='calculation',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='user_input',
        ),
        migrations.AlterField(
            model_name='groups',
            name='price_type',
            field=models.CharField(choices=[(1, 'Only use the group price'), (2, 'Only use the options price'), (3, 'Add the group price to the option price'), (4, 'Average the group price to the option price')], default='1', max_length=1, verbose_name='How is the price calculated?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_type',
            field=models.CharField(choices=[(1, 'Only use the product price'), (2, 'Only use the options price'), (3, 'Add the product price to the option price')], default='1', max_length=1, verbose_name='How is the price calculated?'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='home',
            field=models.CharField(default='Highlight', max_length=20, verbose_name='Homepage title'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is it active?'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reason (only for disabled websites)'),
        ),
    ]
