# Generated by Django 3.0.8 on 2020-12-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0039_auto_20201208_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='price_type',
            field=models.CharField(choices=[(1, 'Only use the group price'), (2, 'Sum all the options price'), (3, 'Average all the options price'), (4, 'Add the group price to the sum options price'), (5, 'Add the group price to the average options price')], default='1', max_length=1, verbose_name='How is the price calculated?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_type',
            field=models.CharField(choices=[(1, 'Only use the product price'), (2, 'Sum all the groups price'), (3, 'Average all the groups price'), (4, 'Add the product price to the sum groups price'), (5, 'Add the product price to the average groups price')], default='1', max_length=1, verbose_name='How is the price calculated?'),
        ),
    ]
