# Generated by Django 3.0.8 on 2020-12-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0040_auto_20201208_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='options',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
