# Generated by Django 3.0.8 on 2020-12-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0041_auto_20201208_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='minimum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
