# Generated by Django 3.0.8 on 2020-12-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0042_auto_20201208_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='websites',
            name='is_active',
        ),
        migrations.AddField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is available?'),
        ),
        migrations.AddField(
            model_name='websites',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is available?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reason (optional, only for unavailable)'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reason (optional, only for unavailable)'),
        ),
    ]
