# Generated by Django 3.0.8 on 2020-12-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0043_auto_20201208_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='show_home',
            field=models.BooleanField(default=True, verbose_name='Show in homepage?'),
        ),
    ]
