# Generated by Django 3.0.8 on 2020-12-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0044_auto_20201208_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='price_type',
            field=models.CharField(choices=[(1, 'Only use the group price'), (2, 'Sum all the options price'), (3, 'Average all the options price'), (4, 'Add the group price to the sum options price'), (5, 'Add the group price to the average options price')], default=1, max_length=1, verbose_name='How is the price calculated?'),
        ),
    ]
