# Generated by Django 3.0.8 on 2020-12-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0048_auto_20201209_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='price_type',
            field=models.CharField(choices=[('1', 'Only use the product price'), ('2', 'Add the product price to the sum groups price'), ('3', 'Add the product price to the average groups price'), ('4', 'Sum all the groups price'), ('5', 'Average all the groups price')], default=1, max_length=1, verbose_name='How is the price calculated?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_type',
            field=models.CharField(choices=[('1', 'Only use the product price'), ('2', 'Add the product price to the sum groups price'), ('3', 'Add the product price to the average groups price'), ('4', 'Sum all the groups price'), ('5', 'Average all the groups price')], default=1, max_length=1, verbose_name='How is the price calculated?'),
        ),
    ]
