# Generated by Django 3.0.8 on 2020-12-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0051_auto_20201215_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='categories',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
