# Generated by Django 3.0.8 on 2020-12-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0053_auto_20201215_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='active',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='colors',
            name='category',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='colors',
            name='footer',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='colors',
            name='navbar',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='colors',
            name='text',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='colors',
            name='title',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='colors',
            name='title_hover',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
