# Generated by Django 3.0.8 on 2020-12-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0055_auto_20201216_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='social_media_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type a message (e.g. follow us)'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='whatsapp_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type a message (e.g. my whatsapp is)'),
        ),
    ]
