# Generated by Django 3.0.8 on 2020-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0056_auto_20201216_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banners',
            name='title',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telephone, only numbers'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Whatsapp, only numbers (e.g. DD999555566)'),
        ),
    ]
