# Generated by Django 3.0.8 on 2020-12-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0060_websites_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='price_type',
            field=models.CharField(choices=[('1', 'Only use the group price'), ('2', 'Add the group price to the sum options price'), ('3', 'Add the group price to the average options price'), ('4', 'Sum all the options price'), ('5', 'Average all the options price')], default='1', max_length=1, verbose_name='How is the price calculated?'),
        ),
    ]
