# Generated by Django 3.0.8 on 2020-12-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0064_auto_20201220_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='show_home',
        ),
        migrations.AddField(
            model_name='products',
            name='show_on_home',
            field=models.BooleanField(default=True, verbose_name='Show on homepage?'),
        ),
    ]
