# Generated by Django 3.1 on 2020-12-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0066_auto_20201222_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='price',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='promotional_price',
        ),
        migrations.AlterField(
            model_name='groups',
            name='price_type',
            field=models.CharField(blank=True, choices=[('1', 'Sum all the options price'), ('2', 'Average all the options price')], max_length=1, null=True, verbose_name='How is the price calculated?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_type',
            field=models.CharField(choices=[('1', 'Only use the product price'), ('2', 'Add the product price to the sum groups price'), ('3', 'Sum all the groups price')], default='1', max_length=1, verbose_name='How is the price calculated?'),
        ),
    ]
