# Generated by Django 3.1 on 2020-12-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0067_auto_20201229_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price, only numbers'),
        ),
        migrations.AlterField(
            model_name='options',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='promotional price, only numbers'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price, only numbers'),
        ),
        migrations.AlterField(
            model_name='products',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='promotional price, only numbers'),
        ),
    ]
