# Generated by Django 3.1 on 2021-01-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0068_auto_20201230_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='active',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Active category color (hexadecimal): '),
        ),
        migrations.AlterField(
            model_name='colors',
            name='category',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Categories bar color (hexadecimal):'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='footer',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Footer color (hexadecimal): '),
        ),
        migrations.AlterField(
            model_name='colors',
            name='navbar',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Navbar color (hexadecimal): '),
        ),
        migrations.AlterField(
            model_name='colors',
            name='text',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Text color (hexadecimal): '),
        ),
        migrations.AlterField(
            model_name='colors',
            name='title',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Title color (hexadecimal): '),
        ),
        migrations.AlterField(
            model_name='colors',
            name='title_hover',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Mouse hover color (hexadecimal): '),
        ),
    ]
